thephpleague/oauth1-client

- README.md
> Update packagist download badge to use correct vendor name

- src/Client/Server/Bitbucket.php
> Populate missing user fields in BitBucket provider

- README.md
With link to When I Work Intuit's provider.
> Add 3rd party providers section

- src/Client/Server/Uservoice.php
https://github.com/thephpleague/oauth1-client/issues/19
> Added Uservoice server

- src/Client/Server/Magento.php
Hey- Just adding on a bit to Craig's work. Magento supports custom urls for admins so I needed a way to pass these in. Do you guys have any changes you would make to this?
> Added pass in for admin url

- .scrutinizer.yml
- .travis.yml
- composer.json
- src/Client/Server/Magento.php
- src/Client/Server/Server.php
- tests/PlainTextSignatureTest.php
- tests/ServerTest.php
- tests/TrelloServerTest.php
The code quality analyzer kicked up a few complaints. These changes provide some fixes for these complaints.
> Improve code quality

- src/Server/AbstractServer.php
- src/Server/GenericServer.php
- test/src/Server/Fake.php
I overlooked this during my refactor, it is definitely needed!
> [2.0] Add token credentials to resource owner url method signature

- src/Signature/HmacSha1Signature.php
The HmacSha1Signature class was utilizing the `Guzzle\Http\Url` library that was part of Guzzle 3. The project itself did not take a dependency on that specific package, it was instead made available through the dev dependency, `satooshi/php-coveralls`. This seemed a bit odd to me and I don't feel that we need to have a dependency on two different versions of guzzle, especially considering the role the `Url` class was playing in this project. 
I've removed this library and replaced its responsibility. All tests are passing.
> [2.0] Remove utilization of Guzzle Http Url library

- README.md
Added a link to my 500px provider in the README file.
- [Packagist](https://packagist.org/packages/mechant/oauth1-500px)
- [Github](https://github.com/monsieurmechant/oauth1-500px)
> Added a link to the 500px provider.

- src/Tool/Crypto.php
The current method is not cryptographically secure.
https://paragonie.com/blog/2015/07/how-safely-generate-random-strings-and-integers-in-php
> [2.0] Use RandomLib to generate a secure nonce

- src/Client/Server/Magento.php
This allows to get authenticated user info
> Magento: User info endpoint added

- composer.json
- src/Client/Signature/HmacSha1Signature.php
Migrate to guzzlehttp 6 like league/oauth2-client
> Move away from abandoned guzzle 3.x

- README.md
For Wellness REST API Specification 1.5
> Added garmin API oauth client

- .gitignore
- .travis.yml
- composer.json
- phpunit.php
- phpunit.xml
- tests/ClientCredentialsTest.php
- tests/HmacSha1SignatureTest.php
- tests/PlainTextSignatureTest.php
- tests/RsaClientCredentialsTest.php
- tests/RsaSha1SignatureTest.php
- tests/ServerTest.php
- tests/TrelloServerTest.php
- tests/XingServerTest.php
The package has been quite stale for some time. This PR bumps the minimum version from PHP 5.5 up to PHP 7.2, updates test dependencies and Travis build configuration.
- Closes #101
- Fixes #105
> Bump minimum PHP version to 7.2, test in PHP 7.2 - 7.4.

- composer.json
This PR allows installation with Guzzle 6 or Guzzle 7.
- Closes #101
- Closes #105
> Allow installation within Guzzle 7

- README.md
Adds link in documentation to Goodreads provider.
> Add Goodreads provider

- src/Client/Server/Magento.php
I noticed the incorrect SignatureInterface was being imported into the Magento Client, so I corrected it.
> Import correct class into constructor

- composer.json
- src/Credentials/ClientCredentials.php
- src/Credentials/ClientCredentialsInterface.php
- src/Credentials/Credentials.php
- src/Credentials/CredentialsInterface.php
- src/Credentials/RsaClientCredentials.php
- src/Credentials/TemporaryCredentials.php
- src/Credentials/TokenCredentials.php
- src/Server/Bitbucket.php
- src/Server/Magento.php
- src/Server/Server.php
- src/Server/Trello.php
- src/Server/Tumblr.php
- src/Server/Twitter.php
- src/Server/User.php
- src/Server/Uservoice.php
- src/Server/Xing.php
- src/Signature/EncodesUrl.php
- src/Signature/HmacSha1Signature.php
- src/Signature/PlainTextSignature.php
- src/Signature/RsaSha1Signature.php
- src/Signature/Signature.php
- src/Signature/SignatureInterface.php
- tests/ClientCredentialsTest.php
- tests/HmacSha1SignatureTest.php
- tests/PlainTextSignatureTest.php
- tests/ServerTest.php
- tests/TrelloServerTest.php
- tests/XingServerTest.php
- tests/stubs/ServerStub.php
Reverts PHP 7.1+ features within the public API as this broke the package for consumers using inheritence. Fixes #118.
Ref #119
> Revert public API changes introduced in 1.8.0 minor release

- README.md
- src/Server/Server.php
- src/Server/Twitter.php
Reverts thephpleague/oauth1-client#138
> Revert "Add 'x_auth_access_type' parameter for Twitter to change the access level of an application"

- src/Server/User.php
This will solve the deprecation warning for this.
> Add ReturnTypeWillChange for PHP 8.1

- .php_cs.dist
- src/Server/Magento.php
- src/Server/Server.php
- src/Server/Trello.php
- src/Server/Twitter.php
- src/Server/Uservoice.php
fixes https://github.com/thephpleague/oauth1-client/issues/154
> [1.x] Supports PHP 8.4

- src/Server/Twitter.php
> Correctly import SignatureInterface
