thephpleague/oauth1-client

- composer.json
- src/Client/Signature/HmacSha1Signature.php
If trusted hosts are configured (e.g., by [Symfony/FrameworkBundle](http://symfony.com/blog/security-releases-symfony-2-0-24-2-1-12-2-2-5-and-2-3-3-released)), the Symfony `Request::getHost()` method will throw an "untrusted host" exception during HMAC-SHA1 request signing (assuming it's host isn't whitelisted).
Unfortunately, `Request::$trustedHosts` is set statically, which limits how the Request class can be used in this library, when the library is a dependency of a Symfony2 app configured with trusted hosts.
I replaced the Symfony's Request class usage with Guzzle's Url class and directly passed `$method`.
> Use Guzzle Url to avoid trusted host verification issues w/ Symfony Request

- src/Client/Server/Bitbucket.php
- src/Client/Server/Twitter.php
There were empty lines in the Twitter and Bitbucket server classes. This was causing conflicts with Code Sniffer. This PR addresses that.
This may be related to this issue https://github.com/thephpleague/oauth1-client/issues/5
> correcting phpcs errors for extra lines

- src/Client/Server/Bitbucket.php
- src/Client/Server/Server.php
- src/Client/Server/Twitter.php
I am currently working on a OAuth 1 Server to be used in conjunction with this library. The OAuth provider allows for custom meta data to be passed to the authorization url with query string parameters. 
The current behavior of this class is such that it blindly concatenates the `urlAuthorization()` and `http_build_query($parameters)` with a `?` character separator.
I am proposing a change that adds a `buildUrl` method to the Server class. This method will now be used in the `getAuthorizationUrl()` method to return the complete authorization url.
With this change in place new Server implementations can declare urls that include query string parameters that will not break when the base Server class appends the `oauth_token`.
````php
/**
* {@inheritDoc}
*/
public function urlAuthorization() …
```
> Add buildUrl method to Server class

- .scrutinizer.yml
- .travis.yml
- README.md
- composer.json
- src/Client/Server/Trello.php
- tests/TrelloServerTest.php
This request proposes the addition of a Trello OAuth 1 Client Server. This code migrating from https://github.com/stevenmaguire/trello-oauth1-server
I have introduced the new Trello Server class, and a separate supporting test class to cover additional functionality offered by the vendor specific class that is above and beyond the parent Server class. I have also added specific documentation to the Readme for the Trello usage.
I have introduced a Scrutinizer config file, as well as the supporting changes to the Travis config file to provide more visibility in the quality of the code.
> Add Trello server

- .gitignore
- composer.json
- phpunit.xml
- src/Client/Server/Server.php
- tests/ServerTest.php
In response to https://github.com/thephpleague/oauth1-client/issues/8, this PR proposes a solution that includes a new `setUserAgent` method which sets a protected property on the base `Server` class, so all vendor specific implementations can utilize this feature. 
When building the `Authorization` header for each request, the custom header is passed into a `buildHttpClientHeaders` method, where it is merged with a default set of headers. This default set of headers is empty unless the `userAgent` is set, in which case it will include the header in the response.
This solution does not provide a method to unset the `userAgent` property, but the `setUserAgent` method accepts and sets null.
Additionally, the merge is configured in such a way that each of the requesting methods can set …
> adding support for setting user agent

- src/Client/Server/Magento.php
- src/Client/Server/Server.php
New Magento server client with support for regular and admin users.
Magento is unique in that it's not a single service like Twitter or Tumblr, but instead is a hosted instance. This requires us to construct with the base uri of the host. In addition, Magento has two separate authorization urls based on whether we are authenticating as an admin or a store user/customer.
This PR also has a small change to the `protocolHeader()` method to include the `additionalProtocolParameters()`.
> Add a Magento server client

- src/Client/Server/Server.php
- tests/ServerTest.php
- add `Server::getHeaders()` for making authenticated requests
See also thephpleague/oauth2-client#232
> Enhance ability to use client to make authenticated requests

- src/Client/Server/Twitter.php
Since April of this year (2015) Twitter is now able to supply a user's email address, with one caveat - you need to have your app whitelisted.
More information here: https://dev.twitter.com/rest/reference/get/account/verify_credentials
> Add Email for Twitter

- src/Client/Server/Magento.php
I tried to run this code to connect to a local magento installation:
```php
$magento = new \League\OAuth1\Client\Server\Magento(array(
'host' => 'http://127.0.0.1:8080/',
'identifier' => 'identifier',
'secret' => 'secret',
'callback_uri' => 'http://localhost',
'admin' => true, // optional, default false
));
```
* it resulted in an exception as it checked if the host was *not* set, although it is used later on
* the alternative port was not passed to the base url
> fix passing host, and hosts with different port for magento

- src/Client/Server/Twitter.php
Noticed the `id` field was being used for a user's Twitter ID. Twitter highly recommends using the `id_str` field instead due to issues with how large integers are handled in a lot of systems. It's _probably_ not actually an issue in practice in this case, but I've personally run into issues due to this when working with the Twitter API in a Javascript environment, and since it's recommended by their documentation, it seems like it's probably a better choice than using the integer field.
https://dev.twitter.com/overview/api/twitter-ids-json-and-snowflake
> Use id_str instead of id for Twitter IDs

- src/Server/AbstractServer.php
- test/src/Server/AbstractServerTest.php
Previously, the package was sending the `bodyParameters` array directly into the client send method. Now, the `League\OAuth1\Client\Tool\RequestFactory` uses the `GuzzleHttp\Psr7\Request` constructor to build the request, which does not support array body types.
> [2.0] Update post request builder to use json_encoded string

- src/Server/AbstractServer.php
- src/Tool/ArrayAccessorTrait.php
- test/src/Server/AbstractServerTest.php
- test/src/Tool/ArrayAccessorTraitTest.php
The temporary credentials method needs to be POST and I added a ksort to the OAuth Authorization header key-value pairs.
> [2.0] Fixing a couple of issues found during functional testing

- src/Credentials/Credentials.php
- src/Server/GenericResourceOwner.php
- src/Server/GenericServer.php
- src/Signature/HmacSha1Signature.php
- src/Signature/PlainTextSignature.php
- src/Signature/Signature.php
As @shadowhand pointed out in #40 the inline `{@inheritdoc}` only inherits the summary.
Also, the `League\OAuth1\Client\Signature\Signature::__construct` method had a doc inheritance tag. Where is it inheriting from!? :smile:
> [2.0] Update inheritDoc tags to correct format

- phpunit.xml
- src/Credentials/ClientCredentials.php
- src/Credentials/TemporaryCredentials.php
- src/Credentials/TokenCredentials.php
- src/Exceptions/ConfigurationException.php
- src/Exceptions/CredentialsException.php
- src/Server/AbstractServer.php
- test/src/Exceptions/ExceptionsTest.php
Instead of having the exceptions throw themselves, return the exception
instance and let the calling class throw it. This ensures the calling
class retains control and allows code coverage to operate normally.
> [2.0] Clean up exception factory handling

- src/Client/Signature/HmacSha1Signature.php
- tests/HmacSha1SignatureTest.php
With this implementation, multi-dimensional arrays can be passed
to League\OAuth1\Client\Server::getHeaders() and be correctly
transformed. For prior art, consider the [WP REST API - OAuth 1.0a Server](https://github.com/WP-API/OAuth1)
plugin. Specifically:
* [https://github.com/WP-API/OAuth1/blob/master/lib/class-wp-rest-oauth1.php#L667-L674](https://github.com/WP-API/OAuth1/blob/master/lib/class-wp-rest-oauth1.php#L667-L674)
* [https://github.com/WP-API/OAuth1/blob/master/lib/class-wp-rest-oauth1.php#L706-L753](https://github.com/WP-API/OAuth1/blob/master/lib/class-wp-rest-oauth1.php#L706-L753)
Includes tests. (closing #60)
> Allow mult-dimension arrays when generating base string for HMAC-SHA1 signature. Fixes #39

- README.md
This is a fantastic package! We wanted to share the [Xero](https://xero.com) provider we wrote. :)
> Added link to Xero provider

- composer.json
```laravel/socialite``` and others depending on this package display
> **Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.**
so I've update the guzzle dependency.
Tests seem to run just fine
```
gabriel@~:oauth1-client (git:master) $ phpunit
PHPUnit 4.8.26 by Sebastian Bergmann and contributors.
Warning:	The Xdebug extension is not loaded
No code coverage will be generated.
.....................................
Time: 212 ms, Memory: 8.75MB
OK (37 tests, 114 assertions)
```
> Updated dependency in composer.json to use guzzlehttp/guzzle instead of guzzle/guzzle

- .travis.yml
- composer.json
There was really nothing from PHP 7.2 that we specifically required over PHP 7.1, except that PHP 7.1 has reached EOL.
A major consumer of this package, [Laravel Socialite](https://github.com/laravel/socialite) only requires PHP 7.1+, so by restricting a new version to PHP 7.2, we'd be potentially blocking their users from receiving updates.
> Relax from PHP 7.2

- src/Signature/EncodesUrl.php
- tests/HmacSha1SignatureTest.php
Fixes an issue where non-standard ports were not taken into consideration within the base string generation.
Fixes #123.
> Fixes an issue where non-standard ports were not taken into consideration

- .gitattributes
Exclude these files from the composer package. Offers better `vendor` security and smaller downloads.
See https://php.watch/articles/composer-gitattributes#export-ignore
> chore: added .gitattributes

- src/Server/Server.php
- tests/ServerTest.php
Optional authorization URL creation parameter in vain of Oauth2 to be appended to the URL. No change in case you don't use it, if you do, you can add parameters to the authorization URL. 
Resolves #130
> Optional authorization parameters

- tests/Signature/BaseStringBuilderTest.php
Adds a test to prove the base string is consistent with the OAuth spec.
Ref #123.
> Improves base string tests to prove port functionality

- src/Signature/EncodesUrl.php
The `GuzzleHttp\Psr7\uri_for` function is deprecated and removed in Guzzle 7.2.  Where available `GuzzleHttp\Psr7\Utils::uriFor` is used instead.
Given we support Guzzle 6 and 7, both the method and function call are required to be supported.
Fixes #134.
> Remove deprecated Guzzle function call

- README.md
- src/Server/Server.php
- src/Server/Twitter.php
Hey,
I use Socialite on my app and I notice that the 'x_auth_access_type' parameter for Twitter was not handle in your package.
This parameter can be used to define the access level of the application. Here is the documentation about the [Twitter request_token endpoint](https://developer.twitter.com/en/docs/authentication/api-reference/request_token).
I'll need to open a pull request on Socialite as well to handle this modification.
I'm open if you have a better implementation for this that can be handle by Socialite natively.
> Add 'x_auth_access_type' parameter for Twitter to change the access level of an application
